# Assignment:

# Real scenario: Service keeps stopping:

Get-WinEvent -LogName System | Where-Object {$_.ProviderName -eq "Service Control Manager" -and $_.LevelDisplayName -eq "Error"} | Select-Object -Property TimeCreated, Id, Message;




<#
$_.ProviderName
What it is

ProviderName tells you which component generated the event.

In your case:

$_.ProviderName -eq "Service Control Manager"


This means:

“Only include events that were generated by the Service Control Manager (SCM).”

What is Service Control Manager?

SCM is a core Windows component that:

Starts and stops services

Tracks service failures

Logs errors when services fail to start

Common SCM error examples:

A service failed to start

A service timed out

A dependency service is missing

Example Provider Names
Service Control Manager
Microsoft-Windows-Kernel-Power
Microsoft-Windows-WindowsUpdateClient
Disk
Tcpip

$_.LevelDisplayName
What it is

LevelDisplayName is the human-readable severity level of the event.

In your filter:

$_.LevelDisplayName -eq "Error"


This means:

“Only include events with Error severity.”

Common LevelDisplayName values
LevelDisplayName	Meaning
Information	Normal operation
Warning	Potential issue
Error	Something failed
Critical	Serious system failure
Verbose	Detailed diagnostic info
Behind the scenes

Internally, Windows stores this as a numeric level, but PowerShell exposes a friendly name:

Level	Numeric
Critical	1
Error	2
Warning	3
Information	4
Verbose	5
What your full filter means (plain English)
Where-Object {
    $_.ProviderName -eq "Service Control Manager" -and
    $_.LevelDisplayName -eq "Error"
}


👉 Translation:

“Show me only Error-level events that were logged by the Service Control Manager.”

How to see these properties yourself

If you want to explore an event’s properties:

Get-WinEvent -LogName System -MaxEvents 1 | Format-List *


Or list just the key ones:

Get-WinEvent -LogName System -MaxEvents 5 |
Select-Object TimeCreated, ProviderName, LevelDisplayName, Id, Message

Network Engineer perspective (why this matters)

As a network engineer, SCM errors often point to:

Failed network services (DHCP, DNS Client, NLA)

VPN client services failing to start

NIC-related services crashing after boot

Dependencies missing after updates

This filter is exactly what you’d use to troubleshoot:

“Why didn’t my VPN start?”

“Why is DHCP not working after reboot?”

“Why is my server losing network connectivity?”

If you want, I can next:

Show common SCM error IDs

Teach how to filter by a specific service

Explain how to trace service startup dependencies
#>
